### ISSUE TITLE
Create teams

### ISSUE THREAD

**Issue by nguyinh** [Nguyinh/BabyStats#38]
### What is it
Teams are where players would be stored in one area/enterprise/group (like a secret Facebook group), created by a any newcomer on web app.
### Admins
These teams would have an admin by default (the one which created league) and would be independent between each others. This admin could add as much admins as he desires.
### How to add players
Players could be invited by players already in the team or possibly by searching name or team uid

### TODO
- [ ] Set up database (team name - unique id - creation timestamp)
- [ ] Display Statistics of self team
- [ ] Possibility to be member of multiple team
- [ ] Display matchmaking in Live match only if player is member of a team
